language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
  - rbx-3
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
env:
  - JRUBY_OPTS='--debug'
script: bundle exec rake spec
matrix:
  include:
    - name: rubocop
      script: bundle exec rake rubocop
      rvm: 2.3 # always match lowest supported version
